DROP MATERIALIZED VIEW IF EXISTS token_ohlc_usd_24h CASCADE;
DROP MATERIALIZED VIEW IF EXISTS token_ohlc_usd_4h CASCADE;
DROP MATERIALIZED VIEW IF EXISTS token_ohlc_usd_1h CASCADE;
DROP MATERIALIZED VIEW IF EXISTS token_ohlc_usd_5m CASCADE;
DROP MATERIALIZED VIEW IF EXISTS token_ohlc_usd_1m CASCADE;

DROP TABLE IF EXISTS bootstrap_state;
DROP TABLE IF EXISTS sui_usd_1m;

ALTER TABLE pool_liquidity DROP COLUMN IF EXISTS tvl_usd;

ALTER TABLE ohlc_1m
    DROP COLUMN IF EXISTS open_usd,
    DROP COLUMN IF EXISTS high_usd,
    DROP COLUMN IF EXISTS low_usd,
    DROP COLUMN IF EXISTS close_usd,
    DROP COLUMN IF EXISTS volume_usd;

ALTER TABLE swaps_fact
    DROP COLUMN IF EXISTS amount_usd,
    DROP COLUMN IF EXISTS price_usd_per_base;
