DROP MATERIALIZED VIEW IF EXISTS token_volume_24h CASCADE;
DROP MATERIALIZED VIEW IF EXISTS token_volume_6h CASCADE;
DROP MATERIALIZED VIEW IF EXISTS token_volume_1h CASCADE;
DROP MATERIALIZED VIEW IF EXISTS ohlc_24h CASCADE;
DROP MATERIALIZED VIEW IF EXISTS ohlc_4h CASCADE;
DROP MATERIALIZED VIEW IF EXISTS ohlc_1h CASCADE;
DROP MATERIALIZED VIEW IF EXISTS ohlc_5m CASCADE;
