DROP MATERIALIZED VIEW IF EXISTS token_ohlc_usd_30m CASCADE;
DROP MATERIALIZED VIEW IF EXISTS token_ohlc_usd_15m CASCADE;
DROP MATERIALIZED VIEW IF EXISTS ohlc_30m CASCADE;
DROP MATERIALIZED VIEW IF EXISTS ohlc_15m CASCADE;
