global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: sui-token-indexer
    static_configs:
      - targets: ["host.docker.internal:9184"]
  - job_name: sui-processors
    static_configs:
      - targets: ["host.docker.internal:9185"]
  - job_name: sui-volume-engine
    static_configs:
      - targets: ["host.docker.internal:9186"]
  - job_name: sui-ohlc-aggregator
    static_configs:
      - targets: ["host.docker.internal:9187"]
