global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: sui-token-indexer
    static_configs:
      - targets: ["host.docker.internal:9184"]
  - job_name: sui-processors
    static_configs:
      - targets: ["host.docker.internal:9185"]
  - job_name: sui-volume-engine
    static_configs:
      - targets: ["host.docker.internal:9186"]
  - job_name: sui-api-service
    static_configs:
      - targets: ["host.docker.internal:9188"]
  - job_name: sui-rolloff-job
    static_configs:
      - targets: ["host.docker.internal:9189"]
  - job_name: sui-oracle-bootstrap
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:9190"]
